// import { QueryEngine } from '@comunica/query-sparql'
import { pickIfcItemsByGUIDs } from './app.js'
import { pickIfcItemByGUID } from './app.js'

import { createSubsetByType } from './app.js' //test

export async function selectElementsStatus() {
    // const myEngine = new QueryEngine();
    // const graphs = document.getElementById("GRAPH-input").value.split(',')
    // const bindingsStream = await myEngine.queryBindings(`
    // PREFIX bot: <https://w3id.org/bot#> 
    // PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
    // PREFIX nen2660: <https://w3id.org/nen2660/def#>
    // PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
    // PREFIX rii: <https://janssensteenberg.com/rii#>
    // PREFIX omg: <https://w3id.org/omg#>
    // PREFIX schema: <http://schema.org/>
    // PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
    // PREFIX cto: <https://w3id.org/cto#>
    // PREFIX dot: <https://w3id.org/dot#>
    // PREFIX prov: <http://www.w3.org/ns/prov#>
    // PREFIX fog: <https://w3id.org/fog#>
    
    // Select Distinct ?label ?GUIDs ?type
    // WHERE {
    //        ?ifcElement fog:hasIfcId-guid ?GUIDs  ;
    //                 rdfs:label ?label .
        
    //     ?task rdfs:label ?type ;
    //              prov:endedAtTime ?DateTime . 
        
    //     {    
    //     SELECT Distinct ?label (MAX(?dateTime) AS ?maxDateTime)
    //         WHERE {
    //             ?element cto:isSubjectOfTask ?task ;
    //                      rdfs:label ?label .
    //               ?task prov:endedAtTime ?dateTime .        
    //         }      
    //     GROUP BY ?label
    //       }
      
    //       FILTER (?DateTime = ?maxDateTime)   
    // }
    
    //   `, {
    //     sources: graphs,
    // });
    

    // const results = [];
    // bindingsStream.on('data', (binding) => {
    //     const guid = binding.get('GUIDs').value;
    //     const label = binding.get('label').value;
    //     const type = binding.get('type').value;
    //     results.push({guid, label, type});
    //     console.log({guid, label, type});
    // });
    // bindingsStream.on('end', () => {
        console.log(results);
        // pickIfcItemsByGUIDs(results.map((result) => result.guid));
        createSubsetByType(results); //test

        const table = document.createElement('table');
        const headerRow = table.insertRow();
        const headerCellObject = headerRow.insertCell();
        headerCellObject.innerHTML = '<b>Object ID</b>';
        const headerCellType = headerRow.insertCell();
        headerCellType.innerHTML = '<b>Last completed task</b>';
        results.forEach(({ guid, label, type }) => {
            const row = table.insertRow();
            const labelCell = row.insertCell();
            labelCell.innerHTML = label;
            labelCell.classList.add('label-cell');  
            labelCell.onclick = () => {
              pickIfcItemByGUID(guid);
            };
            const TypeCell = row.insertCell();
            TypeCell.innerHTML = type; 
        });
        document.getElementById('results-box-content').appendChild(table);
    
    // });

}
window.selectElementsStatus = selectElementsStatus;
selectElementsStatus()


const results = [ 
    { "label" : "LL1.1", "guid" : "2LFgko5tn7kQ4XTuD09hCM", "type" : "Herplaatsing" },
    { "label" : "LL1.10", "guid" : "19iWHhh_H5mAKJZCHJfgxv", "type" : "Opname Bestaande Situatie" },
    { "label" : "LL1.11", "guid" : "2lfglGM$PDpeAFapxMxqKs", "type" : "Opname Bestaande Situatie" },
    { "label" : "LL1.12", "guid" : "0W5XYKF4P6xw6djUii$6$d", "type" : "Opname Bestaande Situatie" },
    { "label" : "LL1.13", "guid" : "3VwFCTyQDDzRqKFVhgsRZ5", "type" : "Opname Bestaande Situatie" },
    { "label" : "LL1.14", "guid" : "1sW96$ke9FnxH98cridEuE", "type" : "Opname Bestaande Situatie" },
    { "label" : "LL1.15", "guid" : "2AZ0AtaGr1vQEOvjUUvnaN", "type" : "Opname Bestaande Situatie" },
    { "label" : "LL1.17", "guid" : "1y3_1zvuXA1Afg31Usp9WV", "type" : "Opname Bestaande Situatie" },
    { "label" : "LL1.18", "guid" : "1WwVgRgsTA$R0_bKbIvRuF", "type" : "Opname Bestaande Situatie" },
    { "label" : "LL1.19", "guid" : "1NEE9jgyfCzePsVm_6GMTm", "type" : "Opname Bestaande Situatie" },
    { "label" : "LL1.2", "guid" : "0XWAZu1qTAR9U5oGGs5I_v", "type" : "Herplaatsing" },
    { "label" : "LL1.20", "guid" : "1vSjjBOmT31uJEdbjuTDvr", "type" : "Opname Bestaande Situatie" },
    { "label" : "LL1.21", "guid" : "2KQ99Vqq5BGB92dC0fPCbC", "type" : "Opname Bestaande Situatie" },
    { "label" : "LL1.22", "guid" : "0pZcYd3zD06AFo10pQDanI", "type" : "Opname Bestaande Situatie" },
    { "label" : "LL1.23", "guid" : "0CIWpEzpj1He60MIKbhTQs", "type" : "Opname Bestaande Situatie" },
    { "label" : "LL1.3", "guid" : "3Mubo4Gqv7L8T0gxZYw9$2", "type" : "Herplaatsing" },
    { "label" : "LL1.4", "guid" : "14_7gQOsX1oPLItrGaM6Wk", "type" : "Herplaatsing" },
    { "label" : "LL1.5", "guid" : "10y7ujHNP1q9yyJeFGVVnt", "type" : "Herplaatsing" },
    { "label" : "LL1.6", "guid" : "0Cjz$eKzTC$fx76GX0pubV", "type" : "Herplaatsing" },
    { "label" : "LL1.7", "guid" : "27TyOU0Ob9BPUSjA5b0Yyw", "type" : "Herplaatsing" },
    { "label" : "LL1.8", "guid" : "0TOdMk16P9VfjxNS1jmcqu", "type" : "Herplaatsing" },
    { "label" : "LL1.9", "guid" : "2U05awk9z37Aml9_gGbElo", "type" : "Opname Bestaande Situatie" },
    { "label" : "LR1.1", "guid" : "1ubp6ptJD9rfXhc3daXliW", "type" : "Herplaatsing" },
    { "label" : "LR1.10", "guid" : "0CzTi9Wd16iAMRIwngSl19", "type" : "Herplaatsing" },
    { "label" : "LR1.11", "guid" : "0mep4OgI97QfbzG0$cGfWB", "type" : "Herplaatsing" },
    { "label" : "LR1.12", "guid" : "0x$krZ_J5CKebtrKVP4n$r", "type" : "Herplaatsing" },
    { "label" : "LR1.13", "guid" : "36Nbwzhx944ff7khdpVwzE", "type" : "Herplaatsing" },
    { "label" : "LR1.14", "guid" : "0s3SRl7WD4JQwYw5mpwWC0", "type" : "Herplaatsing" },
    { "label" : "LR1.15", "guid" : "2xWqNh7aTDKQJAbib2m8AU", "type" : "Herplaatsing" },
    { "label" : "LR1.16", "guid" : "1egsOLrX91JwNKj4o9HZsT", "type" : "Herplaatsing" },
    { "label" : "LR1.17", "guid" : "2vlFBnV0j96eLwjmjh1NJ9", "type" : "Herplaatsing" },
    { "label" : "LR1.18", "guid" : "2km3B2MLjCGuZCqwBvHECy", "type" : "Herplaatsing" },
    { "label" : "LR1.19", "guid" : "3lMsP0WNvDNQ8cZdJunX3_", "type" : "Herplaatsing" },
    { "label" : "LR1.2", "guid" : "2v$s4nMD50xxy26Nw9lbbM", "type" : "Herplaatsing" },
    { "label" : "LR1.20", "guid" : "1yhhmKDhz9H9Mj_m4Z0ag$", "type" : "Herplaatsing" },
    { "label" : "LR1.21", "guid" : "0$1EaXHSj4PxoKrIhV1olw", "type" : "Herplaatsing" },
    { "label" : "LR1.22", "guid" : "00kL0lH4n3GRg$W2C0ZONA", "type" : "Herplaatsing" },
    { "label" : "LR1.23", "guid" : "1c$wZD1uv9qwjcc8Y2P7Ho", "type" : "Herplaatsing" },
    { "label" : "LR1.24", "guid" : "2E85W$o3DCtu629nG_sJDp", "type" : "Herplaatsing" },
    { "label" : "LR1.3", "guid" : "1rVxmaHBX0vglbYkr77ckP", "type" : "Herplaatsing" },
    { "label" : "LR1.4", "guid" : "1Zl2dgIbz8Rwfbw47lim2x", "type" : "Opname Bestaande Situatie" },
    { "label" : "LR1.5", "guid" : "1ASdrRbjf8Hwtb4RBEiWGP", "type" : "Herplaatsing" },
    { "label" : "LR1.6", "guid" : "2DwlwuuZj6Evj78EOkr4cy", "type" : "Herplaatsing" },
    { "label" : "LR1.7", "guid" : "1sPmW2d2j08fktDOam82$6", "type" : "Herplaatsing" },
    { "label" : "LR1.8", "guid" : "2vrs$d$lL5ShChuXu9ykI2", "type" : "Herplaatsing" },
    { "label" : "LR1.9", "guid" : "1qWo_dJIv8IR5vHfJc$Bvz", "type" : "Herplaatsing" },
    { "label" : "P1.1", "guid" : "1qsRj4doLFpuinsXjnAyUT", "type" : "Herplaatsing" },
    { "label" : "P1.10", "guid" : "0Do_Ip7OL9F8Vo0fEVcX09", "type" : "Herplaatsing" },
    { "label" : "P1.100", "guid" : "1frBOpNrL7iQ7j_y2BJc_T", "type" : "Herplaatsing" },
    { "label" : "P1.101", "guid" : "3sEfq3$Bn0TgKP9e82vZIc", "type" : "Herplaatsing" },
    { "label" : "P1.102", "guid" : "1eIIhB2EHEB9DY7nidzqXj", "type" : "Herplaatsing" },
    { "label" : "P1.103", "guid" : "0p8ZjUVaD8DwDzy8ex$QNz", "type" : "Herplaatsing" },
    { "label" : "P1.104", "guid" : "0lutYvN_f2aR6fBaVavhPK", "type" : "Herplaatsing" },
    { "label" : "P1.105", "guid" : "2bCf_F1612IfRMxn$mNRIz", "type" : "Herplaatsing" },
    { "label" : "P1.106", "guid" : "1i1Ltki9f2ng6SwotzWhjs", "type" : "Herplaatsing" },
    { "label" : "P1.107", "guid" : "0CSaUb6b1BtQV95s5KgpV_", "type" : "Herplaatsing" },
    { "label" : "P1.108", "guid" : "2LUWL9Knn2zQe5gHUNgyUg", "type" : "Herplaatsing" },
    { "label" : "P1.109", "guid" : "2f5jNX4GD4WRnk2nXgNylv", "type" : "Herplaatsing" },
    { "label" : "P1.11", "guid" : "2TTQqT$0v9PBy8g8417C2h", "type" : "Herplaatsing" },
    { "label" : "P1.110", "guid" : "2vOUtlZrT99RA4WqI0Wd_$", "type" : "Herplaatsing" },
    { "label" : "P1.111", "guid" : "2FyICjdCr5CxVsrnsFA5HA", "type" : "Herplaatsing" },
    { "label" : "P1.112", "guid" : "0AMkpZp7H0oOIRrwuzVZc6", "type" : "Herplaatsing" },
    { "label" : "P1.113", "guid" : "3FPr$jWrDBtf7eT3u_Ixg_", "type" : "Herplaatsing" },
    { "label" : "P1.114", "guid" : "3q7r3nBFjFAQ1sfWzSPSOb", "type" : "Herplaatsing" },
    { "label" : "P1.115", "guid" : "0JiHgVWaL5C9_$aOWi0bK9", "type" : "Herplaatsing" },
    { "label" : "P1.116", "guid" : "2dhllO3BbCmgnMS88oxC3o", "type" : "Herplaatsing" },
    { "label" : "P1.117", "guid" : "01tPuMD8T6FQ5sQzDU8ota", "type" : "Herplaatsing" },
    { "label" : "P1.118", "guid" : "22JvrJvBv8JgIsC2Qr0crh", "type" : "Herplaatsing" },
    { "label" : "P1.119", "guid" : "2W$Kjbio1ERfuAEwMs5yN0", "type" : "Herplaatsing" },
    { "label" : "P1.12", "guid" : "34tUZz2Jn5bAG5ojpM58ai", "type" : "Herplaatsing" },
    { "label" : "P1.120", "guid" : "1OABCqXjrDax73e3heqDhI", "type" : "Herplaatsing" },
    { "label" : "P1.121", "guid" : "1i7B1hkK13AwSjEaJmBqug", "type" : "Herplaatsing" },
    { "label" : "P1.122", "guid" : "3K6hMqI2X8mezXQnadmRij", "type" : "Herplaatsing" },
    { "label" : "P1.123", "guid" : "1KnB8ZrOT9z9wbYh3W4i9$", "type" : "Herplaatsing" },
    { "label" : "P1.124", "guid" : "3dmspEuyjEHu$yVl7S$5Zj", "type" : "Herplaatsing" },
    { "label" : "P1.125", "guid" : "0n4a7wMXj7Uu42h8yg9Wir", "type" : "Herplaatsing" },
    { "label" : "P1.126", "guid" : "0EnYbI7KT6$9pvyjNmoCIT", "type" : "Herplaatsing" },
    { "label" : "P1.127", "guid" : "3xqn55$4X5hRWNDz_Eo1fe", "type" : "Herplaatsing" },
    { "label" : "P1.128", "guid" : "0xj6YpOB53bQ_OddzIJNEp", "type" : "Herplaatsing" },
    { "label" : "P1.129", "guid" : "2yy867YQ90cQO225$WoZap", "type" : "Herplaatsing" },
    { "label" : "P1.13", "guid" : "01MmZdrebBgvl01ECtvZXu", "type" : "Herplaatsing" },
    { "label" : "P1.130", "guid" : "24TJzzC8rD9fdjF8Zd1UiA", "type" : "Herplaatsing" },
    { "label" : "P1.131", "guid" : "0qCmOIte96GO21vmKijCHP", "type" : "Herplaatsing" },
    { "label" : "P1.132", "guid" : "3IF9z7SID4NRIFdOg7sMNm", "type" : "Herplaatsing" },
    { "label" : "P1.133", "guid" : "23S5uYOcjEVhkRqqH0tZbn", "type" : "Herplaatsing" },
    { "label" : "P1.134", "guid" : "3GdlbkYgnFe9G_I9Z98Vc8", "type" : "Herplaatsing" },
    { "label" : "P1.135", "guid" : "1$PRPlVFT20e_DY_uNLz7K", "type" : "Herplaatsing" },
    { "label" : "P1.136", "guid" : "2wPT0AbSL6ye15d7mF$uPM", "type" : "Herplaatsing" },
    { "label" : "P1.137", "guid" : "3vAqExNmT5VvgX_Mxri2i8", "type" : "Herplaatsing" },
    { "label" : "P1.138", "guid" : "3PAbFm9XH11Rc2efB1tXif", "type" : "Herplaatsing" },
    { "label" : "P1.139", "guid" : "1lvXqwRG58WufMteuqSY33", "type" : "Herplaatsing" },
    { "label" : "P1.14", "guid" : "35OaWCA2zCQv2nLVfwr1uE", "type" : "Herplaatsing" },
    { "label" : "P1.140", "guid" : "2vWI6wvl5A0f8_OWh_0wXZ", "type" : "Herplaatsing" },
    { "label" : "P1.141", "guid" : "1IFFpeGSDBCgUeNT6G1HH_", "type" : "Herplaatsing" },
    { "label" : "P1.142", "guid" : "2s4IjT4M5DQObqvIOMvgxP", "type" : "Herplaatsing" },
    { "label" : "P1.143", "guid" : "2Yu77P1_j4Rvrrp2oyXnfN", "type" : "Herplaatsing" },
    { "label" : "P1.144", "guid" : "2pSZY31Pf1RO2t4ORF_Kjr", "type" : "Herplaatsing" },
    { "label" : "P1.145", "guid" : "0h$Fd2yY99sg44c9LUGmeC", "type" : "Herplaatsing" },
    { "label" : "P1.146", "guid" : "3de3o1EID4PxDb8gENqa_z", "type" : "Herplaatsing" },
    { "label" : "P1.147", "guid" : "2vkCykRMf6pu8380_AqwRk", "type" : "Herplaatsing" },
    { "label" : "P1.148", "guid" : "1DRgsjaJb6Rv2ICIllniXC", "type" : "Herplaatsing" },
    { "label" : "P1.149", "guid" : "2QBtFh6zf6eh8FtjeNY7ma", "type" : "Herplaatsing" },
    { "label" : "P1.15", "guid" : "1Jk116f5P4P9j89I3Yf2hS", "type" : "Herplaatsing" },
    { "label" : "P1.150", "guid" : "1J8evmp9TDXgb9WgjHSA6B", "type" : "Herplaatsing" },
    { "label" : "P1.151", "guid" : "1I3oBej8D0WRdyxuPreGJ5", "type" : "Herplaatsing" },
    { "label" : "P1.152", "guid" : "1ub7HUrbXFJO7ixNVb_Loy", "type" : "Herplaatsing" },
    { "label" : "P1.153", "guid" : "0efbMDSk57BRE8PRvYddza", "type" : "Herplaatsing" },
    { "label" : "P1.154", "guid" : "02v6wrR8z2qO0orHYiOh63", "type" : "Herplaatsing" },
    { "label" : "P1.155", "guid" : "00Xrr3bWz1SwxO1sjO8HoE", "type" : "Herplaatsing" },
    { "label" : "P1.156", "guid" : "2V3V6Jx$z2twXdpXybA4Bi", "type" : "Herplaatsing" },
    { "label" : "P1.157", "guid" : "2QeobFUbX0FAX6CDuQgJng", "type" : "Herplaatsing" },
    { "label" : "P1.158", "guid" : "2U8gRSSnnEhQICJpi2cc$n", "type" : "Herplaatsing" },
    { "label" : "P1.159", "guid" : "0otxxOb0L8MwYMl2FzHazR", "type" : "Herplaatsing" },
    { "label" : "P1.16", "guid" : "23C6kS3ofEwRYCvLomgL_5", "type" : "Herplaatsing" },
    { "label" : "P1.160", "guid" : "0npTgDGdTFwO7jLy3yCWKN", "type" : "Herplaatsing" },
    { "label" : "P1.161", "guid" : "24AYrslyHDUupk_2XoU9uF", "type" : "Herplaatsing" },
    { "label" : "P1.162", "guid" : "1QCXF1aKfFSf_SlfZo__uK", "type" : "Herplaatsing" },
    { "label" : "P1.163", "guid" : "3Mc6azCKb3sgjijRGliSrX", "type" : "Herplaatsing" },
    { "label" : "P1.164", "guid" : "0LUi9KnA1FMw$6YLGE6eCO", "type" : "Herplaatsing" },
    { "label" : "P1.165", "guid" : "04eBIUbmvAHBgYlmOGe5Pp", "type" : "Herplaatsing" },
    { "label" : "P1.166", "guid" : "2D186rNs9AyeD41fSRVUOK", "type" : "Herplaatsing" },
    { "label" : "P1.167", "guid" : "0QR07w_2T5gwoIE8j6gwtQ", "type" : "Herplaatsing" },
    { "label" : "P1.168", "guid" : "1FUZ9VM215aRu1rw8QbCFN", "type" : "Herplaatsing" },
    { "label" : "P1.169", "guid" : "3aPapE941A$RvQSUZuIY4V", "type" : "Herplaatsing" },
    { "label" : "P1.17", "guid" : "3KYxByAcLDHhbCPnlLICAo", "type" : "Herplaatsing" },
    { "label" : "P1.170", "guid" : "2mqOFyF0rFVfiA2yGczFr4", "type" : "Herplaatsing" },
    { "label" : "P1.171", "guid" : "2VmuFeLl13R8wkPYjuCiMu", "type" : "Herplaatsing" },
    { "label" : "P1.172", "guid" : "0eByyb5HP1a9rNpV01SAOt", "type" : "Herplaatsing" },
    { "label" : "P1.173", "guid" : "0t4qC$SW19F8SM0mTRNPLN", "type" : "Herplaatsing" },
    { "label" : "P1.174", "guid" : "0BfgkdNcLDyuCnGmwgl3sL", "type" : "Herplaatsing" },
    { "label" : "P1.175", "guid" : "1G11qXlcX2DeQN$vwpQv3Z", "type" : "Herplaatsing" },
    { "label" : "P1.176", "guid" : "2cWiBW5DLEFRXc4ONuwUVk", "type" : "Herplaatsing" },
    { "label" : "P1.177", "guid" : "3HZ43sblH3E95v0_VC0ywX", "type" : "Herplaatsing" },
    { "label" : "P1.178", "guid" : "0Z8Fnl1zH7b9h$T95Nbedw", "type" : "Herplaatsing" },
    { "label" : "P1.179", "guid" : "0V8r9JQtb3HwWkslSlbcJD", "type" : "Herplaatsing" },
    { "label" : "P1.18", "guid" : "16$726aT99IOyx_KmtnbfV", "type" : "Herplaatsing" },
    { "label" : "P1.180", "guid" : "1Iiy2OKar2rBYdOqfvVXV5", "type" : "Herplaatsing" },
    { "label" : "P1.181", "guid" : "29YTo7khr3jwB7lQN9L89I", "type" : "Herplaatsing" },
    { "label" : "P1.182", "guid" : "2oewXG2j1CdRe0kTq$QIM1", "type" : "Herplaatsing" },
    { "label" : "P1.183", "guid" : "3NK6Qvio1BDBOekFT6mums", "type" : "Herplaatsing" },
    { "label" : "P1.184", "guid" : "1zHYF3EcT0M9D4jh0ujP2u", "type" : "Herplaatsing" },
    { "label" : "P1.185", "guid" : "0khVJieu5BMPSSLqAzIGiY", "type" : "Herplaatsing" },
    { "label" : "P1.186", "guid" : "0Ui2d13FP1KwsGpwwjuE5P", "type" : "Herplaatsing" },
    { "label" : "P1.187", "guid" : "2GJgIPKmn9uQTS7I411$LW", "type" : "Herplaatsing" },
    { "label" : "P1.188", "guid" : "36rENsS2j7NQOL6QUIApvR", "type" : "Herplaatsing" },
    { "label" : "P1.189", "guid" : "07uzdNPMb4wBbzTWZ2YRPZ", "type" : "Herplaatsing" },
    { "label" : "P1.19", "guid" : "09_gPMTi51_egTHBbRrRFa", "type" : "Herplaatsing" },
    { "label" : "P1.190", "guid" : "1k7nWa6nP96OOqXl3xMfu9", "type" : "Herplaatsing" },
    { "label" : "P1.191", "guid" : "04WGNAM_zD1gUVINOFzoh0", "type" : "Herplaatsing" },
    { "label" : "P1.192", "guid" : "3CZE2ofwD0OA2mwz2MPuzA", "type" : "Herplaatsing" },
    { "label" : "P1.193", "guid" : "3kfAqClqX5fwouEC3iqOe$", "type" : "Herplaatsing" },
    { "label" : "P1.194", "guid" : "0Shhg1xXvE3vHN5o820YSz", "type" : "Herplaatsing" },
    { "label" : "P1.195", "guid" : "0q491UK_D9QPMmG_MBIU$b", "type" : "Herplaatsing" },
    { "label" : "P1.196", "guid" : "1Ahx4O_gzAxeDOTShDtted", "type" : "Herplaatsing" },
    { "label" : "P1.197", "guid" : "2L2MyX0h5ANvhChYLLuNCT", "type" : "Herplaatsing" },
    { "label" : "P1.198", "guid" : "362C8brR50jAHpa$clG2OW", "type" : "Herplaatsing" },
    { "label" : "P1.199", "guid" : "1hua61Hxr549nw0s$g5SBK", "type" : "Herplaatsing" },
    { "label" : "P1.2", "guid" : "24EXTHZkDFOucE2D3rJTiQ", "type" : "Herplaatsing" },
    { "label" : "P1.20", "guid" : "3paSPiXRb8eOl_aaErwysK", "type" : "Herplaatsing" },
    { "label" : "P1.200", "guid" : "09nyYfk8P6QwjiRN$80mku", "type" : "Herplaatsing" },
    { "label" : "P1.201", "guid" : "1eQKODnvT31u3AyVvFBZtF", "type" : "Herplaatsing" },
    { "label" : "P1.202", "guid" : "3HpLihMX1Arf_TChFRli01", "type" : "Herplaatsing" },
    { "label" : "P1.203", "guid" : "1TEZmM3P95ZeUQdrQGh1f5", "type" : "Herplaatsing" },
    { "label" : "P1.204", "guid" : "2kotaXPaH4ZwvQ_ER0npzh", "type" : "Herplaatsing" },
    { "label" : "P1.205", "guid" : "3w1IUYugP5QOB8UAFiyXAX", "type" : "Herplaatsing" },
    { "label" : "P1.206", "guid" : "38MHMcy8TClxytvWFivHme", "type" : "Herplaatsing" },
    { "label" : "P1.207", "guid" : "2sXFmsrljCkQ7GoVPsMPDg", "type" : "Herplaatsing" },
    { "label" : "P1.208", "guid" : "3V1ppy3iTBLBhJ5FvZrKXk", "type" : "Herplaatsing" },
    { "label" : "P1.209", "guid" : "1yRlxU6o99KvWWxCmGjFeK", "type" : "Herplaatsing" },
    { "label" : "P1.21", "guid" : "0EAi3h3_T52Rn1bv_P7kE2", "type" : "Herplaatsing" },
    { "label" : "P1.210", "guid" : "0HT_RyT8fAUuvgX$XBeiqw", "type" : "Herplaatsing" },
    { "label" : "P1.211", "guid" : "2jOZ$2l31359PIaB_xNEsL", "type" : "Herplaatsing" },
    { "label" : "P1.212", "guid" : "24GgOVS9TFOg$vnWTiQObH", "type" : "Herplaatsing" },
    { "label" : "P1.213", "guid" : "2hRqXISL1CyBPghmgb_XPl", "type" : "Herplaatsing" },
    { "label" : "P1.214", "guid" : "2hiVQhi6PA3ONhTzhvSa46", "type" : "Herplaatsing" },
    { "label" : "P1.215", "guid" : "28fP$SGdH09gcGbNNspqjt", "type" : "Herplaatsing" },
    { "label" : "P1.216", "guid" : "0DMGCj$eP64fd2qiiqrr4j", "type" : "Herplaatsing" },
    { "label" : "P1.217", "guid" : "3iWvEWazPBNQXg3NIkUKHd", "type" : "Herplaatsing" },
    { "label" : "P1.218", "guid" : "3C16bFfKz9X81yNaIkYwHL", "type" : "Herplaatsing" },
    { "label" : "P1.219", "guid" : "1_uKwF_ob0wAV07O2Kgmq4", "type" : "Herplaatsing" },
    { "label" : "P1.22", "guid" : "1f0cB69Ov1wh_Z$ctw5MDf", "type" : "Herplaatsing" },
    { "label" : "P1.220", "guid" : "08vjwyFaf48OCbyAI3Ahm0", "type" : "Herplaatsing" },
    { "label" : "P1.221", "guid" : "0VWMxcV$X3X8uxkpwOWPIt", "type" : "Herplaatsing" },
    { "label" : "P1.222", "guid" : "2khXBCUrHDgOcEwZenReD$", "type" : "Herplaatsing" },
    { "label" : "P1.223", "guid" : "0IkbfWfaT969rhyO7IqT9X", "type" : "Herplaatsing" },
    { "label" : "P1.224", "guid" : "2dKMkOKWPD_Avl00OZyLT2", "type" : "Herplaatsing" },
    { "label" : "P1.225", "guid" : "1kA3yCbbXBPwygTTUFpTh_", "type" : "Herplaatsing" },
    { "label" : "P1.226", "guid" : "08JhQbd9D68BAzr1Oyzj3L", "type" : "Herplaatsing" },
    { "label" : "P1.227", "guid" : "0Uilwe27T2feTNI6blCj$b", "type" : "Herplaatsing" },
    { "label" : "P1.228", "guid" : "0wxXzeE8P31vzmAbeJ3wAK", "type" : "Herplaatsing" },
    { "label" : "P1.229", "guid" : "0rVWeGR1zBFhEzdct9ntfy", "type" : "Herplaatsing" },
    { "label" : "P1.23", "guid" : "3ZriemDAH9zBta6UVQGaMV", "type" : "Herplaatsing" },
    { "label" : "P1.230", "guid" : "3cMaeteWn7_RxsrpZtZ1q7", "type" : "Herplaatsing" },
    { "label" : "P1.231", "guid" : "2It$FMD9rCivZPMnaCBSWO", "type" : "Herplaatsing" },
    { "label" : "P1.232", "guid" : "3iuK1_Yf55Vvp_YodNfmRV", "type" : "Herplaatsing" },
    { "label" : "P1.233", "guid" : "23xWd7IyT82Rrg0DTbswpk", "type" : "Herplaatsing" },
    { "label" : "P1.234", "guid" : "3knuDxO9fFOOz8tNPVv5y2", "type" : "Herplaatsing" },
    { "label" : "P1.235", "guid" : "3kfJrpI0j0OfxRFM0VNkse", "type" : "Herplaatsing" },
    { "label" : "P1.236", "guid" : "3Ncuzt6mf3BQBGwgf_By8f", "type" : "Herplaatsing" },
    { "label" : "P1.237", "guid" : "2x8fBK_FnAQ83Qi8TjOa7y", "type" : "Herplaatsing" },
    { "label" : "P1.238", "guid" : "0p65VxJfH8jRAWsVAa56NA", "type" : "Herplaatsing" },
    { "label" : "P1.239", "guid" : "3aEOxIs$X4xu1NG9$NDe49", "type" : "Herplaatsing" },
    { "label" : "P1.24", "guid" : "2zuqz8xGv9dfTHx6Z3Hv5Q", "type" : "Herplaatsing" },
    { "label" : "P1.3", "guid" : "1fzx_Q8cn5rvPiXPeUrW$D", "type" : "Herplaatsing" },
    { "label" : "P1.30", "guid" : "10RJVZfhT7OxQLgj3_NYFL", "type" : "Herplaatsing" },
    { "label" : "P1.36", "guid" : "2gVQtXQ711nuVieTIqcM8U", "type" : "Herplaatsing" },
    { "label" : "P1.4", "guid" : "0xmZ0OtMD8xOYHaj4GNd7X", "type" : "Herplaatsing" },
    { "label" : "P1.49", "guid" : "0mWYLJZz512f0EqyVLzDYk", "type" : "Opname Bestaande Situatie" },
    { "label" : "P1.5", "guid" : "2DKsgwdpL9uxACzLw04Aaq", "type" : "Herplaatsing" },
    { "label" : "P1.50", "guid" : "13hFgEfx9EkfOGk32t4oZI", "type" : "Opname Bestaande Situatie" },
    { "label" : "P1.6", "guid" : "0apPoEgJH56PjoUtgAlkTr", "type" : "Herplaatsing" },
    { "label" : "P1.67", "guid" : "0JrkiB4t1CU9AbYA_kihlm", "type" : "Herplaatsing" },
    { "label" : "P1.68", "guid" : "2iPWeFrVnAAPh9O_V0dH9M", "type" : "Herplaatsing" },
    { "label" : "P1.69", "guid" : "2rYOmlNpf58xosWov4T1NJ", "type" : "Herplaatsing" },
    { "label" : "P1.7", "guid" : "2Lvn64quH5ghqgy7EpzEEV", "type" : "Herplaatsing" },
    { "label" : "P1.70", "guid" : "0lW$Rb6Nb6s9EMMKU$Uxez", "type" : "Herplaatsing" },
    { "label" : "P1.71", "guid" : "1nQxtSFx55xgyGd$3IbHWP", "type" : "Herplaatsing" },
    { "label" : "P1.72", "guid" : "20ESS7tjj39v$SuVRogHub", "type" : "Herplaatsing" },
    { "label" : "P1.73", "guid" : "0l90KJAKX33xq2djA1N1C9", "type" : "Opname Bestaande Situatie" },
    { "label" : "P1.73", "guid" : "0l90KJAKX33xq2djA1N1C9", "type" : "Herplaatsing" },
    { "label" : "P1.74", "guid" : "1owFLUyjX2AvWQIVU_g3iD", "type" : "Opname Bestaande Situatie" },
    { "label" : "P1.74", "guid" : "1owFLUyjX2AvWQIVU_g3iD", "type" : "Herplaatsing" },
    { "label" : "P1.75", "guid" : "3Vd6bruor78RRimy6QNVKS", "type" : "Herplaatsing" },
    { "label" : "P1.76", "guid" : "07TXstdmTCM8X$zbCpo52F", "type" : "Opname Bestaande Situatie" },
    { "label" : "P1.77", "guid" : "2JsP0YPPD2ggZYt_wZQDiC", "type" : "Herplaatsing" },
    { "label" : "P1.78", "guid" : "0tc6wCfof15OjDrUR0ETMk", "type" : "Herplaatsing" },
    { "label" : "P1.79", "guid" : "0g_Bnt1_P8HumKze7$ROsE", "type" : "Herplaatsing" },
    { "label" : "P1.8", "guid" : "0bGGAj6w58xvltQB5RhVUP", "type" : "Herplaatsing" },
    { "label" : "P1.80", "guid" : "0UQqj2jtD8YQhmxMmnph1N", "type" : "Herplaatsing" },
    { "label" : "P1.81", "guid" : "3$KB7TsIj0GAKxIPJegxyl", "type" : "Herplaatsing" },
    { "label" : "P1.82", "guid" : "33zIiVUN58mxq_SZogtR8Q", "type" : "Herplaatsing" },
    { "label" : "P1.83", "guid" : "0y8VN0cB5E3Q$g_YA5BlBB", "type" : "Herplaatsing" },
    { "label" : "P1.84", "guid" : "0_SkkcT7L36fqNwv7ieKLO", "type" : "Herplaatsing" },
    { "label" : "P1.85", "guid" : "2KQzlixFHFw85oYWGfI9Ez", "type" : "Herplaatsing" },
    { "label" : "P1.86", "guid" : "1pOzFwAHL8D8TcSNO30Hf_", "type" : "Herplaatsing" },
    { "label" : "P1.87", "guid" : "3qfptWU51Cu99$5gI8$JE3", "type" : "Herplaatsing" },
    { "label" : "P1.88", "guid" : "3yu6A_1x14EPcrbZnoQl8v", "type" : "Opname Bestaande Situatie" },
    { "label" : "P1.89", "guid" : "2uFczU26b5rhJtHZ6wTP2w", "type" : "Herplaatsing" },
    { "label" : "P1.9", "guid" : "2rj1phHdT4CPUA7YWMv_SF", "type" : "Herplaatsing" },
    { "label" : "P1.90", "guid" : "3gZD9riSPDYf0lha6C6qaw", "type" : "Herplaatsing" },
    { "label" : "P1.91", "guid" : "241hkSqFf7Iu9fsrdd36P_", "type" : "Herplaatsing" },
    { "label" : "P1.92", "guid" : "3oPFe_wFn8bvsNCZOY8RzK", "type" : "Herplaatsing" },
    { "label" : "P1.93", "guid" : "3yNm5sbJj6veyAOvS$r9w4", "type" : "Herplaatsing" },
    { "label" : "P1.94", "guid" : "0jNXFi_GTBO8XaEm_lNJqI", "type" : "Herplaatsing" },
    { "label" : "P1.95", "guid" : "1ybSOuJUb0dgdRfaB6gt$t", "type" : "Herplaatsing" },
    { "label" : "P1.96", "guid" : "0dOsnDxDj0Fe3augsPO8xb", "type" : "Herplaatsing" },
    { "label" : "P1.97", "guid" : "1no4c136P1kOITH0weZBn2", "type" : "Herplaatsing" },
    { "label" : "P1.98", "guid" : "277sc2UjvEbvmkymjeX9bx", "type" : "Herplaatsing" },
    { "label" : "P1.99", "guid" : "0gxqnQgMb0FB2rS$NSURYb", "type" : "Herplaatsing" },
    { "label" : "W1.1", "guid" : "1hrowgJUj82RRcQTGR4i6$", "type" : "Opname Bestaande Situatie" },
    { "label" : "W1.10", "guid" : "1DVGiirG98QwxzGZqPxQQM", "type" : "Herplaatsing" },
    { "label" : "W1.11", "guid" : "2$VNSwa4L8xvdWC80kVIHV", "type" : "Herplaatsing" },
    { "label" : "W1.12", "guid" : "31seVX8vjCJh6b4nIYNCI1", "type" : "Herplaatsing" },
    { "label" : "W1.13", "guid" : "0gDZJstVf0wPBlBqTOgSfT", "type" : "Herplaatsing" },
    { "label" : "W1.14", "guid" : "2H9RZyPID2iRpht2ElHSbv", "type" : "Herplaatsing" },
    { "label" : "W1.15", "guid" : "16wdZeZ_T6b92cLQM$n2CL", "type" : "Herplaatsing" },
    { "label" : "W1.16", "guid" : "1bcvrnqpj2LvRTKMOhUrIc", "type" : "Herplaatsing" },
    { "label" : "W1.17", "guid" : "18hY0hv9f49OAOcClNQyst", "type" : "Herplaatsing" },
    { "label" : "W1.18", "guid" : "36PqszjJ54suDNgJ4nkz3G", "type" : "Herplaatsing" },
    { "label" : "W1.19", "guid" : "2tRCNOMdH0HAHFJdmtXPdb", "type" : "Opname Bestaande Situatie" },
    { "label" : "W1.2", "guid" : "3kuJ6dCh5BpwqzlgrhSDJ8", "type" : "Herplaatsing" },
    { "label" : "W1.20", "guid" : "3gHoRyPZ1DvAOxG4AcsTWh", "type" : "Herplaatsing" },
    { "label" : "W1.21", "guid" : "0V26G40QH20vswmJWpuSty", "type" : "Herplaatsing" },
    { "label" : "W1.22", "guid" : "3qwvzU1CDAeOEYuOcvhufq", "type" : "Herplaatsing" },
    { "label" : "W1.23", "guid" : "0osY0xHGPANAYt2RxRFeZr", "type" : "Herplaatsing" },
    { "label" : "W1.24", "guid" : "3JGPQ7ZQb1xBoVdqn0DQQu", "type" : "Herplaatsing" },
    { "label" : "W1.25", "guid" : "1a$Ffl4y17E96OnEG$JNlt", "type" : "Herplaatsing" },
    { "label" : "W1.26", "guid" : "1XBLJfC9j0Tw7CoNokMSt2", "type" : "Herplaatsing" },
    { "label" : "W1.27", "guid" : "3Giq0NgyX0XOA6JL38OFTG", "type" : "Herplaatsing" },
    { "label" : "W1.28", "guid" : "3Dd$CBqBX7D9Xop83OTVzW", "type" : "Herplaatsing" },
    { "label" : "W1.29", "guid" : "2LQrLjM$P0VBpy0tjUZxwy", "type" : "Herplaatsing" },
    { "label" : "W1.3", "guid" : "023qQS0$v2PRvwmsroYku1", "type" : "Herplaatsing" },
    { "label" : "W1.30", "guid" : "29vexGID93hBudmHBBU7$5", "type" : "Herplaatsing" },
    { "label" : "W1.31", "guid" : "2frsIqpAvDef15JTjpi5p9", "type" : "Herplaatsing" },
    { "label" : "W1.32", "guid" : "3pZfy7CLnBmuhgzcY7hHjF", "type" : "Herplaatsing" },
    { "label" : "W1.33", "guid" : "2JWn0Qm6fAb9oPsExHZSg9", "type" : "Herplaatsing" },
    { "label" : "W1.34", "guid" : "3GIgBfYlrAqB7Y0hMotfDw", "type" : "Herplaatsing" },
    { "label" : "W1.35", "guid" : "3ZlALeWUr3mhc7Tsr34ODI", "type" : "Herplaatsing" },
    { "label" : "W1.36", "guid" : "3qXBmMk1b3sRbzlXZwLmzF", "type" : "Herplaatsing" },
    { "label" : "W1.4", "guid" : "3fO8jFYrf3geJE8K4CtYf8", "type" : "Herplaatsing" },
    { "label" : "W1.5", "guid" : "0kiGWLRjbCqwXkykk92wU9", "type" : "Herplaatsing" },
    { "label" : "W1.6", "guid" : "0urSIL8gD3dfk2g656uYLF", "type" : "Opname Bestaande Situatie" },
    { "label" : "W1.7", "guid" : "0jl2UBVIbB9R7udmBme0By", "type" : "Herplaatsing" },
    { "label" : "W1.8", "guid" : "2iHNWFjp9Dyu8SGtBx2E9_", "type" : "Herplaatsing" },
    { "label" : "W1.9", "guid" : "3nGbZbd9n3zeXT27DxWnls", "type" : "Herplaatsing" },
    { "label" : "W2.1", "guid" : "17z9O9u7r2Ju$UXIkSMDBp", "type" : "Herplaatsing" },
    { "label" : "W2.10", "guid" : "3t2Sj$2qH44Pq0rkN33qvc", "type" : "Herplaatsing" },
    { "label" : "W2.11", "guid" : "2ftQPLOMHDJgvE_sPIlHA5", "type" : "Herplaatsing" },
    { "label" : "W2.12", "guid" : "3aH_kB6Nv7_efp4UUbLT$W", "type" : "Herplaatsing" },
    { "label" : "W2.13", "guid" : "1X2Jvymj1CthacQU$sJ$Yk", "type" : "Herplaatsing" },
    { "label" : "W2.14", "guid" : "2PHSiIAmbCEev2Ju6DBP9h", "type" : "Herplaatsing" },
    { "label" : "W2.15", "guid" : "1$BvLwx_956hM1i0D_RnWw", "type" : "Herplaatsing" },
    { "label" : "W2.16", "guid" : "0oFAUjvZz84RTKPnkCpnBo", "type" : "Herplaatsing" },
    { "label" : "W2.17", "guid" : "1loEb0ySnE6P9xZ4ugvvmU", "type" : "Herplaatsing" },
    { "label" : "W2.19", "guid" : "2IgmNRZff4BQ76ELUQhxhA", "type" : "Herplaatsing" },
    { "label" : "W2.2", "guid" : "3_uj_CEvL4CRlLScr2YSOi", "type" : "Herplaatsing" },
    { "label" : "W2.20", "guid" : "1ZJFGpHAz1hgBkt0NSq$zO", "type" : "Herplaatsing" },
    { "label" : "W2.21", "guid" : "1Bo94nghb0qghCV6uc1Y9y", "type" : "Herplaatsing" },
    { "label" : "W2.22", "guid" : "1JvYEbQ0XBSRarruiSFK9h", "type" : "Herplaatsing" },
    { "label" : "W2.23", "guid" : "3N22kMQTrAIOzaPP1HdYc7", "type" : "Herplaatsing" },
    { "label" : "W2.24", "guid" : "1Zj5TsTBj0guLVFnXyXNIC", "type" : "Herplaatsing" },
    { "label" : "W2.25", "guid" : "0yuNUbS$rEP9xh$TPC4yck", "type" : "Herplaatsing" },
    { "label" : "W2.26", "guid" : "10lGj6Y2PFn93gIJNU6n9H", "type" : "Herplaatsing" },
    { "label" : "W2.27", "guid" : "1Ui3BJDPT9N8neXXc6n0Lm", "type" : "Herplaatsing" },
    { "label" : "W2.28", "guid" : "3VU0hL$h1Do9kagCTAKrP0", "type" : "Opname Bestaande Situatie" },
    { "label" : "W2.29", "guid" : "1Io$nRjUnFwvxKX7yZLUP5", "type" : "Herplaatsing" },
    { "label" : "W2.3", "guid" : "0_kLoGuaX9qRlH2mp7uoF_", "type" : "Herplaatsing" },
    { "label" : "W2.30", "guid" : "3Okegz9bDDLvihlCD$nA66", "type" : "Herplaatsing" },
    { "label" : "W2.31", "guid" : "1QKscWn2P7yeojqkdQLMEs", "type" : "Herplaatsing" },
    { "label" : "W2.32", "guid" : "1w_Nyg$wP9l9Y95u8SggOu", "type" : "Herplaatsing" },
    { "label" : "W2.33", "guid" : "3bn7OhlOnA_Bvdk5KxMWsg", "type" : "Herplaatsing" },
    { "label" : "W2.34", "guid" : "1qmtvuIq92EeIfxiAHbU5Y", "type" : "Herplaatsing" },
    { "label" : "W2.35", "guid" : "3ya7MRG1r4LRc$vv3SZaC8", "type" : "Herplaatsing" },
    { "label" : "W2.36", "guid" : "0DN8BKsyTEA8BNXijTyMeX", "type" : "Herplaatsing" },
    { "label" : "W2.37", "guid" : "0KW65A3EnE1RFe6Jogonjz", "type" : "Herplaatsing" },
    { "label" : "W2.38", "guid" : "303$VgTOH4FAanue0Snn1r", "type" : "Herplaatsing" },
    { "label" : "W2.39", "guid" : "1QLmubt0f0gQ0WH$fMicKr", "type" : "Herplaatsing" },
    { "label" : "W2.4", "guid" : "0GH0$_QSLCd8UqDVBTUWUV", "type" : "Herplaatsing" },
    { "label" : "W2.40", "guid" : "30J1DafMnFLvNitRTfhw$n", "type" : "Herplaatsing" },
    { "label" : "W2.41", "guid" : "3pKLYvgMf4RuEtImmD2NYR", "type" : "Herplaatsing" },
    { "label" : "W2.42", "guid" : "3cU7iSdB50xPD1qGdNzRj1", "type" : "Herplaatsing" },
    { "label" : "W2.43", "guid" : "1sIQt89urAHh_va9QJq78d", "type" : "Herplaatsing" },
    { "label" : "W2.44", "guid" : "1krQ5hIWP4AgTS60Ulp_xf", "type" : "Herplaatsing" },
    { "label" : "W2.45", "guid" : "18xPrAlS93sQDRZ5ddATwx", "type" : "Herplaatsing" },
    { "label" : "W2.46", "guid" : "05KD_HK8jC_wJc0soBlw$B", "type" : "Herplaatsing" },
    { "label" : "W2.47", "guid" : "1uY6WwHe5DABxQXxuEfZdV", "type" : "Herplaatsing" },
    { "label" : "W2.48", "guid" : "3NzvRRBaH2BOO_gpCkrSf7", "type" : "Herplaatsing" },
    { "label" : "W2.49", "guid" : "3wGbLGnojBFwr6JODLK_aU", "type" : "Herplaatsing" },
    { "label" : "W2.5", "guid" : "3X6JS8Ksf279ATZ2yFlUaI", "type" : "Herplaatsing" },
    { "label" : "W2.50", "guid" : "00cNHHxwfBOQx8Bpktk8Ga", "type" : "Herplaatsing" },
    { "label" : "W2.51", "guid" : "2DVrStwkHCKOTkHEJnVkQB", "type" : "Herplaatsing" },
    { "label" : "W2.52", "guid" : "2Sf7OJ_497jPl1HBGMj550", "type" : "Herplaatsing" },
    { "label" : "W2.53", "guid" : "1jxHOMBo9DPA$8hQ8H7c$3", "type" : "Herplaatsing" },
    { "label" : "W2.54", "guid" : "0TJRkGPN93t88sEav$_YBn", "type" : "Herplaatsing" },
    { "label" : "W2.55", "guid" : "2bg9yux05FHuwDWFhnwQyc", "type" : "Herplaatsing" },
    { "label" : "W2.56", "guid" : "0dJFEHOfj7XABe0MwZXdZf", "type" : "Herplaatsing" },
    { "label" : "W2.57", "guid" : "0Tx9Olfq95mRaaRAtRB9Lk", "type" : "Herplaatsing" },
    { "label" : "W2.58", "guid" : "2wkB7QUjbFceLXzZsetAyN", "type" : "Herplaatsing" },
    { "label" : "W2.59", "guid" : "1wwlZYgn14cQKHCj$T1Apa", "type" : "Herplaatsing" },
    { "label" : "W2.6", "guid" : "1YtmC45HT0TxGLrBB9Mwmp", "type" : "Herplaatsing" },
    { "label" : "W2.60", "guid" : "0h1C3x3CL4qvxZY_RFknUX", "type" : "Herplaatsing" },
    { "label" : "W2.61", "guid" : "3R0z$sM7PEuu90G76JhnHp", "type" : "Herplaatsing" },
    { "label" : "W2.62", "guid" : "1DcVfval14N99$Y6UQxWan", "type" : "Herplaatsing" },
    { "label" : "W2.63", "guid" : "0I0HtRSLf26OPiUi1Thewq", "type" : "Herplaatsing" },
    { "label" : "W2.64", "guid" : "2p5KQ6nDLDaQA33Cq$GSgu", "type" : "Herplaatsing" },
    { "label" : "W2.65", "guid" : "0OQ5gfk7D8zR2AfPgb8Wto", "type" : "Herplaatsing" },
    { "label" : "W2.7", "guid" : "1xRYqo_Wj3bABgYcyBqLce", "type" : "Opname Bestaande Situatie" },
    { "label" : "W2.8", "guid" : "0J5Gk_wob0cPEHTHjyf3__", "type" : "Opname Bestaande Situatie" },
    { "label" : "W2.9", "guid" : "0ZCDIG_PXCBunzIJLZhQZJ", "type" : "Herplaatsing" },
    { "label" : "W3.1", "guid" : "10Ikm5gAD2zAKYw4OwZWuo", "type" : "Herplaatsing" },
    { "label" : "W3.2", "guid" : "2PjGAUtMb1XAlKoVtFsOdR", "type" : "Herplaatsing" },
    { "label" : "W3.3", "guid" : "0i1faJGN54Cg68mf1AFRIX", "type" : "Herplaatsing" },
    { "label" : "W3.4", "guid" : "2GZP2InRf9_9SzgAoRgnnD", "type" : "Herplaatsing" },
    { "label" : "W3.5", "guid" : "2NL4i_8mvB2ue8veK8neZ7", "type" : "Herplaatsing" },
    { "label" : "W3.6", "guid" : "3eu2h7_194YQpxOldEg_OD", "type" : "Herplaatsing" },
    { "label" : "W3.7", "guid" : "2JyYAxNpnCaPOxIMp4dAgj", "type" : "Herplaatsing" },
    { "label" : "W3.8", "guid" : "1OUhihhuXBpOCQsIqdbVYx", "type" : "Herplaatsing" },
    { "label" : "W4.1", "guid" : "3_5_tCADL128Ss9bphRIQS", "type" : "Herplaatsing" },
    { "label" : "W4.10", "guid" : "0vdSJWLJ913eypkIydLVyZ", "type" : "Herplaatsing" },
    { "label" : "W4.11", "guid" : "2niEknHRf1b9O2aCDMB_nh", "type" : "Herplaatsing" },
    { "label" : "W4.12", "guid" : "0C3qYL0pf4OhHNq2p5O4Wx", "type" : "Herplaatsing" },
    { "label" : "W4.13", "guid" : "2X6ank5Y16tQlVGJy1B9Gy", "type" : "Herplaatsing" },
    { "label" : "W4.14", "guid" : "3YsDT_Ga19UQn2AKw0PyPq", "type" : "Herplaatsing" },
    { "label" : "W4.2", "guid" : "2LuyVKfZL9ZR8gHT0N4qKC", "type" : "Herplaatsing" },
    { "label" : "W4.3", "guid" : "3dGOyzlq5Aq8JTvL5zdTLE", "type" : "Herplaatsing" },
    { "label" : "W4.4", "guid" : "0pyZNYANj0Bv$KeruxfgkQ", "type" : "Herplaatsing" },
    { "label" : "W4.5", "guid" : "3CuFX9EUrFMAJKVS2UzVj$", "type" : "Herplaatsing" },
    { "label" : "W4.6", "guid" : "0NdZXR1pbAkxoc5dDVpx$2", "type" : "Herplaatsing" },
    { "label" : "W4.7", "guid" : "0OgeLRa0zAd8eDNiR4iv$R", "type" : "Herplaatsing" },
    { "label" : "W4.8", "guid" : "0oTXDP92zEKuGV14f6BG5H", "type" : "Herplaatsing" },
    { "label" : "W4.9", "guid" : "2D4TFyXV97xBsbobJN_aTw", "type" : "Herplaatsing" }
]
